name: Bug Report
description: File a bug report
title: "[SC64][BUG] "
labels: ["bug"]
assignees:
  - Polprzewodnikowy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: sanity-check
    attributes:
      label: Is your issue really a bug?
      description: |
        Issue tracker in this repository is for **BUG REPORTS ONLY**.

        Make sure your problem is caused by the firmware/PC app and **not** by the software you're running on the flashcart.

        Errors in the documentation are also considered a bug.

        If your issue is related to the menu then report it in the [N64FlashcartMenu] repository.

        [N64FlashcartMenu]: https://github.com/Polprzewodnikowy/N64FlashcartMenu
      options:
        - label: I understand the difference between flashcart firmware, N64FlashcartMenu and `sc64deployer` PC app.
          required: true
        - label: I found a bug in FPGA HDL (`/fw/rtl`)
        - label: I found a bug in MCU app (`/sw/controller`)
        - label: I found a bug in N64 bootloader (`/sw/bootloader`)
        - label: I found a bug in PC app (`/sw/deployer`)
        - label: I found a bug in initial programming script (`/sw/tools/primer.py`)
        - label: I found an error in documentation (`/docs`)
        - label: I found an issue elsewhere
  - type: input
    id: version
    attributes:
      label: Firmware version
      placeholder: v2.20.2
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: |
        Tell us what you noticed as a bug, and what is your expected outcome.
        The more detailed the description is the better.
        If applicable please attach screenshots and/or video showing the problem.
    validations:
      required: true
  - type: textarea
    id: deployer-info
    attributes:
      label: Output logs from `sc64deployer info`
      description: If possible, please copy and paste the output from the command specified above.
      render: shell
